[flavor]
use = "tokyonight-night"

# Theme overrides
[manager]
tab_active   = { fg = "#16161e", bg = "#7aa2f7" }
tab_inactive = { fg = "#7aa2f7", bg = "#414868" }

[mode]
normal_main = { fg = "#16161e", bg = "#7aa2f7", bold = true }
normal_alt = { fg = "#7aa2f7", bg = "#414868", bold = true }
select_main = { fg = "#16161e", bg = "#bb9af7", bold = true }
select_alt = { fg = "#bb9af7", bg = "#414868", bold = true }
unset_main = { fg = "#16161e", bg = "#9ece6a", bold = true }
unset_alt = { fg = "#9ece6a", bg = "#414868", bold = true }
