[mgr]
linemode = "size"

[opener]
comic = [
  { run = "flatpak run com.yacreader.YACReader %s", orphan = true, for = "linux" },
]
video = [
  { run = "mpv %s", orphan = true, for = "linux" },
]

[open]
prepend_rules = [
  { url = "*.cbz", use = "comic" },
  { url = "*.cbr", use = "comic" },
  { mime = "video/*", use = "video" },
]
